language: node_js
node_js:
  - node

dist: bionic
sudo: required

notifications:
  email:
    recipients:
      - tf.tan24@gmail.com
    on_success: always
    on_failure: always
branches:
  only:
   - development
before_script:
  - npm install -g @angular/cli
  - ng lint

script:
  - ng build --prod --base-href https://tianiefunie.github.io/bitcoin-order-app/

after_success:
  - npm audit fix


  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GitHubToken
  local_dir: dist/bitcoin
  on:
    branch: development
